;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        hungry-backspace
        tagedit-insert-equal
        ))

(setq mc/cmds-to-run-once
      '(
        ))
