;;setting
(require 'keybinding)
(require 'mode-mapping)
(require 'appearance)
(require 'behavior)

;;ehack
(require 'setup-ido)
(require 'setup-project)
(require 'setup-ggtags)
(require 'setup-company)
(require 'setup-tern)
(require 'setup-smartparens)
(require 'setup-flycheck)
(require 'setup-yas)
(require 'setup-emmet)
(require 'setup-imenu)
(require 'setup-paredit)
(require 'setup-shell)
(require 'setup-hideshow)
(require 'setup-perspective)
(require 'setup-magit)
(require 'setup-default)
(when is-mac (require 'setup-mac))

;;site-lisp
(require 'indent-guide)
(require 'js2-mode)
(require 'ggtags)
(require 'flycheck)
(require 'smartparens-config)
(require 'powerline)
(require 'rainbow-delimiters)
(require 'imenu-anywhere)
(require 'ace-jump-mode)
(require 'expand-region)
(require 's)
(require 'dash)
(require 'goto-last-change)
(require 'shell-pop)
(require 'multi-term)
(require 'eyebrowse)
(require 'zone-matrix)
(require 'zone-settings)
(require 'tabbar)
(require 'sublimity)
(require 'sublimity-scroll)
(require 'sublimity-map)
(require 'sublimity-attractive)
(require 'neotree)
(require 'ztree)
(require 'undo-tree)
(require 'helm)
(require 'async)
(require 'nyan-mode)
(require 'dired-async)
(require 'helm-config)
(require 'helm-swoop)
(require 'names)
(require 'aggressive-indent)
(require 'company-web-html)
(require 'quick-buffer-switch)
(require 'smart-forward)
(require 'browse-kill-ring)
(require 'line-num)
(require 'tagedit)

(require 'setup-aggressive)

;;my site-lisp
(require 'transparent)
(require 'hippie)
(require 'js2-extra)
(require 'html-extra)
(require 'edit-sword)

(require 'trigger)
(provide 'component)
