(require 'haskell-font-lock)
(require 'ghc-core)
(require 'ghci-script-mode)
(require 'haskell-align-imports)
(require 'haskell-cabal)
(require 'haskell-checkers)
(require 'haskell-collapse)
(require 'haskell-commands)
(require 'haskell-compat)
(require 'haskell-compile)
(require 'haskell-complete-module)
(require 'haskell-completions)
(require 'haskell-customize)
(require 'haskell-debug)
(require 'haskell-decl-scan)
(require 'haskell-doc)
(require 'haskell-font-lock)
(require 'haskell-hoogle)
(require 'haskell-indent)
(require 'haskell-indentation)
(require 'haskell-interactive-mode)
(require 'haskell-lexeme)
(require 'haskell-load)
(require 'haskell-menu)
(require 'haskell-mode-pkg)
(require 'haskell-mode)
(require 'haskell-modules)
(require 'haskell-move-nested)
(require 'haskell-navigate-imports)
(require 'haskell-package)
(require 'haskell-presentation-mode)
(require 'haskell-process)
(require 'haskell-repl)
(require 'haskell-sandbox)
(require 'haskell-session)
(require 'haskell-sort-imports)
(require 'haskell-string)
(require 'haskell-unicode-input-method)
(require 'haskell-utils)
(require 'haskell)
(require 'highlight-uses-mode)
(require 'inf-haskell)
(require 'w3m-haddock)
(require 'haskell-mode)

(add-to-list 'load-path "~/.emacs.d/site-lisp/structured-haskell-mode/elisp")
(require 'shm)

(add-hook 'haskell-mode-hook 'structured-haskell-mode)


(provide 'setup-haskell)
